name: Continuous Integration

on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
      - entrypoint.sh
    branches:
      - master

jobs:
  push-to-docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: elgohr/Publish-Docker-Github-Action@v5
      name: Publish to Docker
      with:
        name: innovaciongascaribe/aws-ecr-action
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        tags: latest,v4
        cache: true
